name: UPPERCLOUD
favicon: null
layout_spectrum: 0.49671
typography_spectrum: 0.5108
title: UPPERCLOUD MEDIA
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00aeef'
    - '#440e62'
    - '#224654'
    - '#b6b6b6'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
